// Auto-generated by .github/workflows/bump-version.yml on every push to main - the number is
// main's total commit count, so it ticks up exactly once per merge. Don't hand-edit; changes
// here get overwritten by the next merge anyway.
export const VERSION = "v51";
